name: Check Tel Links

on:
  workflow_dispatch:
    inputs:
      homepage_url:
        description: "Homepage URL to crawl"
        required: true
        default: "https://example.com"
      phone_numbers:
        description: "Comma-separated list of allowed phone numbers"
        required: true
        default: "+1234567890"

jobs:
  tel_check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (explicitly set to version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify Node.js version 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Playwright Browsers
      - name: Install Playwright browsers
        run: npx playwright install

      # Step 5: Run Playwright Tests
      - name: Run Playwright Tel Link Checker
        run: |
          npx playwright test
